title: Sean Law | Web Developer
email: sean.law.321@gmail.com
description: >
  Sean Law - Web developer portfolio
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://inaesu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  iNaesu

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Collections
collections:
  - projects
  - designs

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - todo.md
  - src
