title: Sean Law | Web Developer
email: sean.law.321@gmail.com
description: >
  Sean Law - Web developer portfolio
baseurl: "/portfolio"
url: "https://inaesu.github.io"
github_username:  iNaesu
markdown: kramdown

plugins:
  - jekyll-feed

collections:
  - projects
  - designs

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - todo.md
  - src

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-autoprefixer
